<a href="https://colab.research.google.com/github/m-tsak/PyTorch-Tutorial-YT/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1


array([[0.77960733, 0.93109904, 0.36921927, 0.28654201],
       [0.87804523, 0.65005557, 0.43708989, 0.08317355],
       [0.01756148, 0.56600934, 0.85420564, 0.32664777]])

In [4]:
np1.dtype


dtype('float64')

# **TENSORS**

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.7301, -0.6911, -0.1834, -1.6721],
        [ 0.9911, -0.0774, -0.9748, -0.0219],
        [ 1.3093, -0.5235,  0.5890,  0.7392]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7796, 0.9311, 0.3692, 0.2865],
        [0.8780, 0.6501, 0.4371, 0.0832],
        [0.0176, 0.5660, 0.8542, 0.3266]], dtype=torch.float64)